#!/bin/sh /etc/rc.common
START=97
STOP=10
USE_PROCD=1

start_service() {
    # Ждём сеть (проверка через ifstatus, не зависит от конкретного внешнего IP)
    local i=0
    while [ $i -lt 15 ]; do
        [ "$(ubus call network.interface.wan status 2>/dev/null | jsonfilter -e '@.up' 2>/dev/null)" = "true" ] && break
        sleep 1
        i=$((i+1))
    done

    # Применяем TPROXY
    sh /etc/tibro/tproxy.sh

    # Применяем DNS записи
    uci delete dhcp.@dnsmasq[0].address 2>/dev/null
    uci add_list dhcp.@dnsmasq[0].address='/youtube.com/198.18.0.1'
    uci add_list dhcp.@dnsmasq[0].address='/googlevideo.com/198.18.0.2'
    uci add_list dhcp.@dnsmasq[0].address='/ytimg.com/198.18.0.3'
    uci add_list dhcp.@dnsmasq[0].address='/googleapis.com/198.18.0.4'
    uci add_list dhcp.@dnsmasq[0].address='/googleusercontent.com/198.18.0.5'
    uci commit dhcp
    /etc/init.d/dnsmasq restart

    # Пересобираем конфиг
    . /etc/tibro/tibro.conf
    sh /etc/tibro/build-config.sh \
        /etc/tibro/nodes/${ACTIVE_PROVIDER}.json \
        $ACTIVE_NODE > /etc/tibro/config.json

    # Запускаем xray через procd
    procd_open_instance
    procd_set_param command /usr/bin/xray -c /etc/tibro/config.json
    procd_set_param limits nofile="65535 65535"
    procd_set_param respawn 30 10 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    sh /etc/tibro/tproxy-stop.sh
}
